#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  $LOAD_PATH << File.expand_path(File.join(__dir__, "..", "lib"))

  require "mux_tf"

  MuxTf::Cli.run(:current, ARGV)
rescue Exception => e
  warn e.full_message
  warn "<press enter>"
  gets
  exit 1
end
