#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  $LOAD_PATH.unshift File.expand_path(File.join(__dir__, "..", "lib"))

  require "deps"
  require "mux_tf"

  MuxTf::Cli.run(:mux, ARGV)
rescue Exception => e
  warn e.full_message
  warn "<press enter>"
  $stdin.gets
  exit 1
end
