name: Publish to Rubygems

on:
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Validate Branch
      if: github.ref != 'refs/heads/master'
      run: "false"

    - uses: rubygems/configure-rubygems-credentials@main
      with:
        role-to-assume: ${{secrets.RUBYGEMS_ROLE_TO_ASSUME}}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        mkdir -p ~/.gem
        touch ~/.gem/credentials
        echo ":github: Bearer ${{secrets.GITHUB_TOKEN}}" >> ~/.gem/credentials
        chmod 0600 ~/.gem/credentials

    - name: Release
      run: |
        rake release

    - name: Cleanup on Error
      if: failure()
      run: |
        TAG=$(git tag --points-at HEAD)
        if [[ "" == "$TAG" ]]; then
          echo "no tag at head, nothing to clean up"
        else
          git tag -d "$TAG"
          git push origin ":$TAG" || true
        fi
