name: Publish to Rubygems

on:
  workflow_dispatch: {}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

    - name: Validate Branch
      if: github.ref != 'refs/heads/master'
      run: "false"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Release Gem
      uses: cadwallion/publish-rubygems-action@master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_PUBLISH_KEY}}
        RELEASE_COMMAND: rake release
