name: Publish to Rubygems

on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Validate Branch
      if: github.ref != 'refs/heads/master'
      run: "false"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :github: Bearer ${{secrets.GITHUB_TOKEN}}
        :rubygems_api_key: ${{secrets.RUBYGEMS_PUBLISH_KEY}}
        EOF
        chmod 0600 ~/.gem/credentials

    - name: Release
      run: |
        rake release

    - name: Cleanup on Error
      if: failure()
      run: |
        # optionally remove the tag that was generated and possibly pushed
        TAG=$(git tag --points-at HEAD)
        if [[ "" == "$TAG" ]]; then
          # no tag, do nothing
        else
          git tag -d "$TAG"
          git push origin ":$TAG" || true
        fi
